package com.lucamartinelli.aentur.persistence;

import com.lucamartinelli.aentur.vo.MonsterDTO;

public class MonstersListDB {

	public static final MonsterDTO[] MONSTERS = new MonsterDTO[] {
			new MonsterDTO(0, "world.enemy.name.wolf", "world.enemy.description.wolf", 1, 
					new Integer[]{0,1,2}, 
					new Integer[]{0,1,2}),
			new MonsterDTO(1, "world.enemy.name.graywolf", "world.enemy.description.wolf", 2, 
					new Integer[]{0,3,5}, 
					new Integer[]{0,1,3}),
			new MonsterDTO(2, "world.enemy.name.goblin", "world.enemy.description.goblin", 1, 
					new Integer[]{1,2,5}, 
					new Integer[]{0,2,10}),
			new MonsterDTO(3, "world.enemy.name.giantant", "world.enemy.description.giantant", 1, 
					new Integer[]{0,4,5}, 
					new Integer[]{0,11,12}),
			new MonsterDTO(4, "world.enemy.name.zombie", "world.enemy.description.zombie", 1, 
					new Integer[]{0,1,2}, 
					new Integer[]{10,12}),
			new MonsterDTO(5, "world.enemy.name.wyvern", "world.enemy.description.wyvern", 1, 
					new Integer[]{2,4,8}, 
					new Integer[]{2,11,14}),
			new MonsterDTO(6, "world.enemy.name.monkeywarrior", "world.enemy.description.monkeywarrior", 1, 
					new Integer[]{1,2,5}, 
					new Integer[]{1,2,4}),
			new MonsterDTO(7, "world.enemy.name.rockgolem", "world.enemy.description.rockgolem", 1, 
					new Integer[]{4,5,12}, 
					new Integer[]{0,13,14}),
			new MonsterDTO(8, "world.enemy.name.ghost", "world.enemy.description.ghost", 1, 
					new Integer[]{2,5,9}, 
					new Integer[]{2,10,14}),
			new MonsterDTO(9, "world.enemy.name.blackrat", "world.enemy.description.blackrat", 1, 
					new Integer[]{0,1,5}, 
					new Integer[]{0,1,5}),
			new MonsterDTO(10, "world.enemy.name.waterspirit", "world.enemy.description.waterspirit", 1, 
					new Integer[]{2,6,9}, 
					new Integer[]{2,9,14}),
			new MonsterDTO(11, "world.enemy.name.wasp", "world.enemy.description.wasp", 1, 
					new Integer[]{5,14,15}, 
					new Integer[]{0,2,15}),
			new MonsterDTO(12, "world.enemy.name.bat", "world.enemy.description.bat", 1, 
					new Integer[]{0,2,5}, 
					new Integer[]{1,2,12}),
			new MonsterDTO(13, "world.enemy.name.caveworm", "world.enemy.description.caveworm", 1, 
					new Integer[]{0,4,12}, 
					new Integer[]{2,11,12}),
			new MonsterDTO(14, "world.enemy.name.magicianapprentice", "world.enemy.description.magicianapprentice", 1, 
					new Integer[]{7,9,11}, 
					new Integer[]{2,10,14}),
			new MonsterDTO(15, "world.enemy.name.imp", "world.enemy.description.imp", 1, 
					new Integer[]{1,8,11}, 
					new Integer[]{2,8,12}),
			new MonsterDTO(16, "world.enemy.name.bigspider", "world.enemy.description.bigspider", 1, 
					new Integer[]{0,14,15}, 
					new Integer[]{0,11,15}),
			new MonsterDTO(17, "world.enemy.name.skeletron", "world.enemy.description.skeletron", 1, 
					new Integer[]{4,5,9}, 
					new Integer[]{10,13,14}),
			new MonsterDTO(18, "world.enemy.name.helldog", "world.enemy.description.helldog", 1, 
					new Integer[]{0,8,11}, 
					new Integer[]{1,2,8}),
			new MonsterDTO(19, "world.enemy.name.slime", "world.enemy.description.slime", 1, 
					new Integer[]{4,7,12}, 
					new Integer[]{9,12,15}),
			new MonsterDTO(20, "world.enemy.name.mushroom", "world.enemy.description.mushroom", 1, 
					new Integer[]{1,12,15}, 
					new Integer[]{0,3,12}),
			new MonsterDTO(21, "world.enemy.name.tentacle", "world.enemy.description.tentacle", 1, 
					new Integer[]{4,5,14}, 
					new Integer[]{2,11,12}),
			new MonsterDTO(22, "world.enemy.name.tiger", "world.enemy.description.tiger", 1, 
					new Integer[]{0,1,4}, 
					new Integer[]{1,2,3}),
			new MonsterDTO(23, "world.enemy.name.darkpixie", "world.enemy.description.darkpixie", 1, 
					new Integer[]{7,9,11}, 
					new Integer[]{2,10,14}),
			new MonsterDTO(24, "world.enemy.name.flyingeye", "world.enemy.description.flyingeye", 1, 
					new Integer[]{3,7,10}, 
					new Integer[]{0,2,14}),
			new MonsterDTO(25, "world.enemy.name.icebear", "world.enemy.description.icebear", 2, 
					new Integer[]{3,6,20}, 
					new Integer[]{3,7,13}),
			new MonsterDTO(26, "world.enemy.name.dragon", "world.enemy.description.dragon", 2, 
					new Integer[]{3,8,19}, 
					new Integer[]{3,14,20}),
			new MonsterDTO(27, "world.enemy.name.bigskeletron", "world.enemy.description.bigskeletron", 2, 
					new Integer[]{4,21,24}, 
					new Integer[]{6,13,14}),
			new MonsterDTO(28, "world.enemy.name.darkmage", "world.enemy.description.darkmage", 2, 
					new Integer[]{7,17,22}, 
					new Integer[]{4,13,16}),
			new MonsterDTO(29, "world.enemy.name.firedaemon", "world.enemy.description.firedaemon", 2, 
					new Integer[]{11,17,19}, 
					new Integer[]{8,16,19}),
			new MonsterDTO(30, "world.enemy.name.troll", "world.enemy.description.troll", 2, 
					new Integer[]{3,4,21}, 
					new Integer[]{3,4,15}),
			new MonsterDTO(31, "world.enemy.name.irongolem", "world.enemy.description.irongolem", 2, 
					new Integer[]{5,21,23}, 
					new Integer[]{0,6,13}),
			new MonsterDTO(32, "world.enemy.name.vampire", "world.enemy.description.vampire", 2, 
					new Integer[]{3,5,22}, 
					new Integer[]{0,5,16}),
			new MonsterDTO(33, "world.enemy.name.gargoyle", "world.enemy.description.gargoyle", 2, 
					new Integer[]{1,3,14}, 
					new Integer[]{0,5,18}),
			new MonsterDTO(34, "world.enemy.name.darkwitch", "world.enemy.description.darkwitch", 2, 
					new Integer[]{15,17,22}, 
					new Integer[]{10,14,16}),
			new MonsterDTO(35, "", "", 1, 
					new Integer[]{}, 
					new Integer[]{}),
	};
	
	public static MonsterDTO getById(int id) {
		return MONSTERS[id].clone();
		
	}

}
