package com.lucamartinelli.aentur.persistence;

import com.lucamartinelli.aentur.vo.MonsterDTO;

public class MonstersListDB {

	public static final MonsterDTO[] MONSTERS = new MonsterDTO[] {
			new MonsterDTO(0, "Lupo", "Un lupo affamato in caccia", 1, 
					new Integer[]{0,1,2}, 
					new Integer[]{0,1,2}),
			new MonsterDTO(1, "Lupo grigio", "Un lupo di dimensioni maggiori affamato in caccia", 2, 
					new Integer[]{0,3,5}, 
					new Integer[]{0,1,3}),
			new MonsterDTO(2, "Goblin", "Un piccolo goblin sbuca dal buio, impugna un coltello e sembra aggressivo", 1, 
					new Integer[]{1,2,5}, 
					new Integer[]{0,2,10}),
			new MonsterDTO(3, "Formica gigante", "Improvvisamente una formica dalle dimensioni di cane medio ti punta", 1, 
					new Integer[]{0,4,5}, 
					new Integer[]{0,11,12}),
			new MonsterDTO(4, "Zombie", "Un puzzolente zombie si presenta lentamente davanti a te emettendo lamenti lugubri", 1, 
					new Integer[]{0,1,2}, 
					new Integer[]{10,12}),
			new MonsterDTO(5, "Piccola Viverna", "Una piccola viverna ti vola sopra la testa prima di atterrarti davanti", 1, 
					new Integer[]{2,4,8}, 
					new Integer[]{2,11,14}),
			new MonsterDTO(6, "Guerriero scimmia", "Una scimmia umanoide verstita tribale e armata ti guarda con aria minacciosa", 1, 
					new Integer[]{1,2,5}, 
					new Integer[]{1,2,4}),
			new MonsterDTO(7, "Golem di roccia", "Un mostruoso golem di pietra blocca la via", 1, 
					new Integer[]{4,5,12}, 
					new Integer[]{0,13,14}),
			new MonsterDTO(8, "Fantasma", "Uno spaventoso fantasma ti guarda con occhi spettrali", 1, 
					new Integer[]{2,5,9}, 
					new Integer[]{2,10,14}),
			new MonsterDTO(9, "Ratto nero", "Un indemoniato ratto nero ti sbava davanti, apre la bocca e mostra le zanne affilate", 1, 
					new Integer[]{0,1,5}, 
					new Integer[]{0,1,5}),
			new MonsterDTO(10, "Spirito d'acqua", "Da una pozza si crea magicamente uno spirito magico acquatico", 1, 
					new Integer[]{2,6,9}, 
					new Integer[]{2,9,14}),
			new MonsterDTO(11, "Vespa assassina", "Un enorme insetto svolazza aggressivo, sembra una vespa delle dimensioni di un gatto", 1, 
					new Integer[]{5,14,15}, 
					new Integer[]{0,2,15}),
			new MonsterDTO(12, "Pipistrello", "Nel buio vedi 2 occhi rossi brillare, in un attimo un grosso pipistrello si libra in aria e carica verso di te", 1, 
					new Integer[]{0,2,5}, 
					new Integer[]{1,2,12}),
			new MonsterDTO(13, "Verme di grotta", "Un grosso verme sbuca dal terreno", 1, 
					new Integer[]{0,4,12}, 
					new Integer[]{2,11,12}),
			new MonsterDTO(14, "Apprendista mago", "Un malvagio mago apprendista crea delle magie per bloccarti", 1, 
					new Integer[]{7,9,11}, 
					new Integer[]{2,10,14}),
			new MonsterDTO(15, "Imp", "Un piccolo demone di fuoco ti guarda con un ghigno spettrale", 1, 
					new Integer[]{1,8,11}, 
					new Integer[]{2,8,12}),
			new MonsterDTO(16, "Grosso Ragno", "Un mostruoso ragno sguscia dalle tenebre e ti attacca", 1, 
					new Integer[]{0,14,15}, 
					new Integer[]{0,11,15}),
			new MonsterDTO(17, "Scheletro", "Uno scheletro barcollante e armato ti blocca la strada", 1, 
					new Integer[]{4,5,9}, 
					new Integer[]{10,13,14}),
			new MonsterDTO(18, "Belva infernale", "Un cane infuocato corre verso di te, deve arrivare direttamente dall'inferno", 1, 
					new Integer[]{0,8,11}, 
					new Integer[]{1,2,8}),
			new MonsterDTO(19, "Melma verde", "Un enorme melma puzzolente copre la via, all'interno fluttuano pezzi di ossa e metalli", 1, 
					new Integer[]{4,7,12}, 
					new Integer[]{9,12,15}),
			new MonsterDTO(20, "Fungo vivente", "Un fungo con fattezze umanoidi, sembra essere molto arrabbiato", 1, 
					new Integer[]{1,12,15}, 
					new Integer[]{0,3,12}),
			new MonsterDTO(21, "Tentacolo", "Un grosso tentacolo sbuca dal terreno, non ha occhi, ma sa esattamente dove sei", 1, 
					new Integer[]{4,5,14}, 
					new Integer[]{2,11,12}),
			new MonsterDTO(22, "Tigre", "Agile e feroce, una tigre ti guarda e ti punta, pronta ad attaccare in qualsiasi momento", 1, 
					new Integer[]{0,1,4}, 
					new Integer[]{1,2,3}),
			new MonsterDTO(23, "Fata oscura", "Malvagia e diabolica, una fata oscura prepara incantesimi demoniaci per l'attacco", 1, 
					new Integer[]{7,9,11}, 
					new Integer[]{2,10,14}),
			new MonsterDTO(24, "Occhio volante", "Spaventoso e disgustoso, l'occhio volante e' in grado di fare male oltre che a spaventare", 1, 
					new Integer[]{3,7,10}, 
					new Integer[]{0,2,14}),
			new MonsterDTO(25, "Orso del ghiaccio", "Un orso il cui pelo e' mischiato con ghiaccio e neve, fa paura e freddo nello stesso istante", 2, 
					new Integer[]{3,6,20}, 
					new Integer[]{3,7,13}),
			new MonsterDTO(26, "Drago", "Un drago di medie dimensioni plana davanti a te", 2, 
					new Integer[]{3,8,19}, 
					new Integer[]{3,14,20}),
			new MonsterDTO(27, "Grosso scheletro guerriero", "Uno scheletro corazzato piu' veloce del solito, blocca la strada e non sembra aver intenzione di lasciar passare nessuno", 2, 
					new Integer[]{4,21,24}, 
					new Integer[]{6,13,14}),
			new MonsterDTO(28, "Mago oscuro", "Un malvagio mago nero crea delle magie per bloccarti", 2, 
					new Integer[]{7,17,22}, 
					new Integer[]{4,13,16}),
			new MonsterDTO(29, "Demone di fuoco", "Un grosso e fiammeggiante demone, emana tanto calore da poter scaldare un castello", 2, 
					new Integer[]{11,17,19}, 
					new Integer[]{8,16,19}),
			new MonsterDTO(30, "Troll", "Un puzzolente ed enorme troll, molto aggressivo senza una particolare ragione per esserlo", 2, 
					new Integer[]{3,4,21}, 
					new Integer[]{3,4,15}),
			new MonsterDTO(31, "Golem di metallo", "Luccicante e spaventoso, i grande golem di metallo ti fissa immobile per qualche istante prima di iniziare l'attacco", 2, 
					new Integer[]{5,21,23}, 
					new Integer[]{0,6,13}),
			new MonsterDTO(32, "Vampiro", "Un vampiro assetato di sangue ti punta e ti vede come una preda", 2, 
					new Integer[]{3,5,22}, 
					new Integer[]{0,5,16}),
			new MonsterDTO(33, "Gargoyle", "Scambiato per una statua, il gargoyle si muove appena ti avvicini", 2, 
					new Integer[]{1,3,14}, 
					new Integer[]{0,5,18}),
			new MonsterDTO(34, "Strega oscura", "Una strega malvagia con intenzioni poco chiare, ma sicuramente non amichvoli", 2, 
					new Integer[]{15,17,22}, 
					new Integer[]{10,14,16}),
			new MonsterDTO(35, "", "", 1, 
					new Integer[]{}, 
					new Integer[]{}),
	};

}
